CONFIG_FILE=$GITHUB_WORKSPACE/diy/configs/$BUILD_VER.config
DIY_SET=$GITHUB_WORKSPACE/diy/settings/$BUILD_VER.settings
DIY_LOGO=$GITHUB_WORKSPACE/diy/imgs/$BUILD_VER.jpg

echo "CONFIG_FILE=$CONFIG_FILE"
echo "DIY_SET=$DIY_SET"
echo "DIY_LOGO=$DIY_LOGO"
