#!/bin/sh

uci set ddns.cf_jimmy=service
uci set ddns.cf_jimmy.enabled='1'
uci set ddns.cf_jimmy.service_name='cloudflare.com-v4'
uci set ddns.cf_jimmy.lookup_host='jimmy.xzhhzx222.com'
uci set ddns.cf_jimmy.domain='jimmy@xzhhzx222.com'
uci set ddns.cf_jimmy.ip_source='interface'
uci set ddns.cf_jimmy.interface='wan'
uci set ddns.cf_jimmy.ip_interface='pppoe-wan'
uci commit ddns

# Delete dhcp.domain
for i in $(seq 0 2);do uci del dhcp.@domain[0];done
# Delete dhcp.host
for i in $(seq 0 4);do uci del dhcp.@host[0];done
# Set dhcp.dnsmasq
uci set dhcp.@dnsmasq[0].cachesize='0'
uci set dhcp.@dnsmasq[0].filter_aaaa='1'
uci set dhcp.@dnsmasq[0].sequential_ip='1'
# Set dhcp.lan
uci set dhcp.lan.start='20'
uci set dhcp.lan.limit='99'
# Add dhcp.domain
for i in $(seq 0 2);do uci add dhcp domain && uci set dhcp.@domain[$i].ip='192.168.0.'$(($i+1))'';done
# Set dhcp.domain
uci set dhcp.@domain[0].name='jimmyesxi.com'
uci set dhcp.@domain[1].name='jimmywrt.com'
uci set dhcp.@domain[2].name='jimmynas.com'
# Add dhcp.host
for i in $(seq 0 4);do uci add dhcp host && uci set dhcp.@host[$i].dns='1' && uci set dhcp.@host[$i].ip='192.168.0.1'$i'' && uci set dhcp.@host[$i].leasetime='infinite';done
# Set dhcp.host
for i in $(seq 1 4);do uci set dhcp.@host[$i].name='Lobby-PC'$i'';done
uci set dhcp.@host[0].name='Jimmy-Server'
uci set dhcp.@host[0].mac='28:e3:47:c3:70:24'
uci set dhcp.@host[1].mac='a8:a1:59:20:60:d5'
uci set dhcp.@host[2].mac='1c:39:47:18:09:2f'
uci set dhcp.@host[3].mac='a8:a1:59:20:60:d7'
uci set dhcp.@host[4].mac='a8:a1:59:20:60:9f'
uci commit dhcp

# Delete firewall.redirect
for i in $(seq 0 13);do uci del firewall.@redirect[0];done
# Delete firewall.zone list
uci del_list firewall.@zone[1].network='wan6'
# Delete firewall.rule
for i in $(seq 3 6);do uci set firewall.@rule[$i].enabled='0';done
# Add firewall.redirect
for i in $(seq 0 13);do uci add firewall redirect && uci set firewall.@redirect[$i].target='DNAT' && uci set firewall.@redirect[$i].src='wan' && uci set firewall.@redirect[$i].dest='lan' && uci set firewall.@redirect[$i].proto='tcp';done
# Adjust firewall.redirect
for i in 7 10;do uci set firewall.@redirect[$i].proto='tcp udp';done
for i in 1 3 11;do uci set firewall.@redirect[$i].enabled='0';done
for i in $(seq 1 4);do uci set firewall.@redirect[$i].dest_ip='192.168.0.2';done
for i in $(seq 5 13);do uci set firewall.@redirect[$i].dest_ip='192.168.0.3';done
# Set firewall.redirect
uci set firewall.@redirect[0].dest_ip='192.168.0.1'
uci set firewall.@redirect[0].src_dport='27443'
uci set firewall.@redirect[0].dest_port='443'
uci set firewall.@redirect[0].name='JimmyEsxi WebUI'
uci set firewall.@redirect[1].src_dport='7981'
uci set firewall.@redirect[1].dest_port='7981'
uci set firewall.@redirect[1].name='JimmyWrt OpenClash Socks'
uci set firewall.@redirect[2].src_dport='9090'
uci set firewall.@redirect[2].dest_port='9090'
uci set firewall.@redirect[2].name='JimmyWrt OpenClash WebUI'
uci set firewall.@redirect[3].src_dport='27022'
uci set firewall.@redirect[3].dest_port='22'
uci set firewall.@redirect[3].name='JimmyWrt SSH'
uci set firewall.@redirect[4].src_dport='27080'
uci set firewall.@redirect[4].dest_port='80'
uci set firewall.@redirect[4].name='JimmyWrt WebUI'
uci set firewall.@redirect[5].src_dport='6800'
uci set firewall.@redirect[5].dest_port='6800'
uci set firewall.@redirect[5].name='JimmyNas aria2 6800'
uci set firewall.@redirect[6].src_dport='6880'
uci set firewall.@redirect[6].dest_port='6880'
uci set firewall.@redirect[6].name='JimmyNas aria2 6880'
uci set firewall.@redirect[7].src_dport='6888'
uci set firewall.@redirect[7].dest_port='6888'
uci set firewall.@redirect[7].name='JimmyNas aria2 6888'
uci set firewall.@redirect[8].src_dport='8999'
uci set firewall.@redirect[8].dest_port='8999'
uci set firewall.@redirect[8].name='JimmyNas qbittorrent 8999'
uci set firewall.@redirect[9].src_dport='9000'
uci set firewall.@redirect[9].dest_port='9000'
uci set firewall.@redirect[9].name='JimmyNas portainer 9000'
uci set firewall.@redirect[10].src_dport='16888'
uci set firewall.@redirect[10].dest_port='16888'
uci set firewall.@redirect[10].name='JimmyNas qbittorrent 16888'
uci set firewall.@redirect[11].src_dport='27023'
uci set firewall.@redirect[11].dest_port='22'
uci set firewall.@redirect[11].name='JimmyNas SSH'
uci set firewall.@redirect[12].src_dport='27081'
uci set firewall.@redirect[12].dest_port='27081'
uci set firewall.@redirect[12].name='JimmyNas traefik 27081'
uci set firewall.@redirect[13].src_dport='27444'
uci set firewall.@redirect[13].dest_port='27444'
uci set firewall.@redirect[13].name='JimmyNas traefik 27444'
uci commit firewall

uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci set luci.main.lang=zh_cn
uci commit luci

uci del network.globals
uci del network.lan.ip6assign
uci del network.wan6
uci set network.lan.ipaddr='192.168.0.2'
uci set network.lan.dns='119.29.29.29 114.114.114.114'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.delegate='0'
uci set network.lan.ifname='eth0 eth1 eth2 eth4 eth5'
uci set network.wan.proto='pppoe'
uci set network.wan.delegate='0'
uci set network.wan.ipv6='0'
uci set network.wan.ifname='eth3'
uci commit network

uci del serverchan.serverchan.cpuload
uci set serverchan.serverchan.serverchan_enable='1'
uci set serverchan.serverchan.serverchan_up='0'
uci set serverchan.serverchan.serverchan_down='0'
uci set serverchan.serverchan.cpuload_enable='0'
uci set serverchan.serverchan.jsonpath='/usr/bin/serverchan/api/qywx_mpnews.json'
uci set serverchan.serverchan.mediapath='/usr/bin/serverchan/api/logo.jpg'
uci set serverchan.serverchan.device_name='JimmyWrt'
uci set serverchan.serverchan.serverchan_ipv4='1'
uci set serverchan.serverchan.ipv4_interface='pppoe-wan'
uci set serverchan.serverchan.web_logged='1'
uci set serverchan.serverchan.ssh_logged='1'
uci set serverchan.serverchan.web_login_failed='1'
uci set serverchan.serverchan.ssh_login_failed='1'
uci set serverchan.serverchan.web_login_black='0'
uci set serverchan.serverchan.login_max_num='3'
uci set serverchan.serverchan.crontab='2'
uci set serverchan.serverchan.interval_time='4'
uci set serverchan.serverchan.send_title='路由状态'
uci set serverchan.serverchan.router_status='1'
uci set serverchan.serverchan.router_temp='0'
uci set serverchan.serverchan.router_wan='1'
uci set serverchan.serverchan.client_list='1'
uci set serverchan.serverchan.serverchan_sheep='2'
uci set serverchan.serverchan.starttime='0'
uci set serverchan.serverchan.endtime='8'
uci commit serverchan

uci set system.@system[0].hostname='JimmyWrt'
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.ntp.enable_server='1'
uci commit system

# Delete timewol.macclient
for i in $(seq 0 3);do uci del timewol.@macclient[0];done
# Add timewol.macclient
for i in $(seq 0 3);do uci add timewol macclient && uci set timewol.@macclient[$i].maceth='br-lan' && uci set timewol.@macclient[$i].minute='30' && uci set timewol.@macclient[$i].hour='10';done
# Set timewol.macclient
uci set timewol.@macclient[0].macaddr='A8:A1:59:20:60:D5'
uci set timewol.@macclient[1].macaddr='1C:39:47:18:09:2F'
uci set timewol.@macclient[2].macaddr='A8:A1:59:20:60:D7'
uci set timewol.@macclient[3].macaddr='A8:A1:59:20:60:9F'
# Set timewol.basic
uci set timewol.@basic[0].enable='1'
uci commit timewol

uci set turboacc.config.bbr_cca='1'
uci commit turboacc

uci set uhttpd.main.rfc1918_filter='0'
uci commit uhttpd

uci set upnpd.config.enabled='1'
uci commit upnpd

# Add wolplus.pc
for i in $(seq 1 4);do uci set wolplus.pc$i=macclient && uci set wolplus.pc$i.name='Lobby-P'C$i'' && uci set wolplus.pc$i.maceth='br-lan';done
# Set wolplus.pc
uci set wolplus.pc1.macaddr='A8:A1:59:20:60:D5'
uci set wolplus.pc2.macaddr='1C:39:47:18:09:2F'
uci set wolplus.pc3.macaddr='A8:A1:59:20:60:D7'
uci set wolplus.pc4.macaddr='A8:A1:59:20:60:9F'
uci commit wolplus

sed -i '/dhcp-option/d' /etc/dnsmasq.conf
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/\"control\"/\"services\"/g' /usr/lib/lua/luci/controller/timewol.lua
sed -i 's/\"control\"/\"services\"/g' /usr/lib/lua/luci/view/timewol/index.htm

sed -i 's/root::0:0:99999:7:::/root:$1$fbr0AcjI$x07b6cfvhGdfFLdbDCcfj.:0:0:99999:7:::/g' /etc/shadow

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='Ver22.07.27'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='JimmyWrt '" >> /etc/openwrt_release

sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
sed -i '/passwall/d' /etc/opkg/distfeeds.conf
sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf

/etc/init.d/softethervpnbridge disable 2>/dev/null
/etc/init.d/softethervpnserver disable 2>/dev/null
/etc/init.d/softethervpnclient disable 2>/dev/null

echo 'hsts=0' > /root/.wgetrc

ln -sf /sbin/ip /usr/bin/ip

rm -rf /tmp/luci-*cache

rm -rf /usr/lib/lua/luci/view/admin_status/index

exit 0
