#!/bin/sh

#uci set ddns.cf_pan=service
#uci set ddns.cf_pan.enabled='1'
#uci set ddns.cf_pan.service_name='cloudflare.com-v4'
#uci set ddns.cf_pan.lookup_host='pan.xzhhzx222.com'
#uci set ddns.cf_pan.domain='pan@xzhhzx222.com'
#uci set ddns.cf_pan.ip_source='interface'
#uci set ddns.cf_pan.interface='wan'
#uci set ddns.cf_pan.ip_interface='pppoe-wan'
#uci commit ddns

# Delete dhcp.domain
for i in $(seq 0 3);do uci del dhcp.@domain[0];done
# Delete dhcp.host
for i in $(seq 0 4);do uci del dhcp.@host[0];done
# Set dhcp.dnsmasq
uci set dhcp.@dnsmasq[0].cachesize='0'
uci set dhcp.@dnsmasq[0].filter_aaaa='1'
uci set dhcp.@dnsmasq[0].sequential_ip='1'
# Set dhcp.lan
uci set dhcp.lan.start='20'
uci set dhcp.lan.limit='99'
uci set dhcp.lan.force='1'
# Add dhcp.domain
for i in $(seq 0 2);do uci add dhcp domain && uci set dhcp.@domain[$i].ip='10.0.0.'$(($i+1))'';done
uci add dhcp domain
# Set dhcp.domain
uci set dhcp.@domain[0].name='samesxi.com'
uci set dhcp.@domain[1].name='samwrt.com'
uci set dhcp.@domain[2].name='samnas.com'
uci set dhcp.@domain[3].ip='10.0.0.3'
uci set dhcp.@domain[3].name='pan.xzhhzx222.com'
# Add dhcp.host
for i in $(seq 0 4);do uci add dhcp host && uci set dhcp.@host[$i].dns='1' && uci set dhcp.@host[$i].ip='10.0.0.1'$i'' && uci set dhcp.@host[$i].leasetime='infinite';done
# Set dhcp.host
uci set dhcp.@host[0].name='Sam-Desktop'
uci set dhcp.@host[0].mac='70:4d:7b:63:0a:37'
uci set dhcp.@host[1].name='Sam-LEGION'
uci set dhcp.@host[1].mac='b0:3c:dc:8c:71:de'
uci set dhcp.@host[2].name='Sophie-XIAOXIN'
uci set dhcp.@host[2].mac='08:5b:d6:b0:76:83'
uci set dhcp.@host[3].name='Mom-Nova6'
uci set dhcp.@host[3].mac='92:bc:db:b7:c6:ce'
uci set dhcp.@host[4].name='Dad-K40S'
uci set dhcp.@host[4].mac='be:36:f0:5e:0f:67'
uci commit dhcp

# Delete firewall.redirect
for i in $(seq 0 10);do uci del firewall.@redirect[0];done
# Delete firewall.zone
for i in 2 2;do uci del firewall.@zone[$i];done
# Delete firewall.zone list
uci del_list firewall.@zone[1].network='wan6'
# Delete firewall.rule
for i in $(seq 3 6);do uci set firewall.@rule[$i].enabled='0';done
# Add firewall.zone
for i in 2 3;do uci add firewall zone && uci set firewall.@zone[$i].input='ACCEPT' && uci set firewall.@zone[$i].output='ACCEPT' && uci set firewall.@zone[$i].forward='ACCEPT';done
# Set firewall.zone
uci set firewall.@zone[2].name='vlan85'
uci set firewall.@zone[2].network='vlan85'
uci set firewall.@zone[3].name='vlan51'
uci set firewall.@zone[3].network='vlan51'
# Add firewall.redirect
for i in $(seq 0 10);do uci add firewall redirect && uci set firewall.@redirect[$i].target='DNAT' && uci set firewall.@redirect[$i].src='wan' && uci set firewall.@redirect[$i].dest='lan' && uci set firewall.@redirect[$i].proto='tcp';done
# Adjust firewall.redirect
for i in 8 12;do uci set firewall.@redirect[$i].proto='tcp udp';done
for i in 3 13;do uci set firewall.@redirect[$i].enabled='0';done
for i in $(seq 1 4);do uci set firewall.@redirect[$i].dest_ip='10.0.0.2';done
for i in $(seq 5 9);do uci set firewall.@redirect[$i].dest_ip='10.0.0.3';done
# Set firewall.redirect
uci set firewall.@redirect[0].dest_ip='10.0.0.1'
uci set firewall.@redirect[0].src_dport='27444'
uci set firewall.@redirect[0].dest_port='443'
uci set firewall.@redirect[0].name='SamEsxi WebUI'
uci set firewall.@redirect[0].enabled='0'
uci set firewall.@redirect[1].src_dport='7893'
uci set firewall.@redirect[1].dest_port='7893'
uci set firewall.@redirect[1].name='SamWrt OpenClash Socks'
uci set firewall.@redirect[1].enabled='1'
uci set firewall.@redirect[2].src_dport='9090'
uci set firewall.@redirect[2].dest_port='9090'
uci set firewall.@redirect[2].name='SamWrt OpenClash WebUI'
uci set firewall.@redirect[2].enabled='0'
uci set firewall.@redirect[3].src_dport='27022'
uci set firewall.@redirect[3].dest_port='22'
uci set firewall.@redirect[3].name='SamWrt SSH'
uci set firewall.@redirect[3].enabled='0'
uci set firewall.@redirect[4].src_dport='22080'
uci set firewall.@redirect[4].dest_port='80'
uci set firewall.@redirect[4].name='SamWrt WebUI'
uci set firewall.@redirect[4].enabled='0'
uci set firewall.@redirect[5].src_dport='16888'
uci set firewall.@redirect[5].dest_port='16888'
uci set firewall.@redirect[5].name='SamNas qbittorrent 16888'
uci set firewall.@redirect[5].enabled='1'
uci set firewall.@redirect[6].src_dport='27023'
uci set firewall.@redirect[6].dest_port='22'
uci set firewall.@redirect[6].name='SamNas SSH'
uci set firewall.@redirect[6].enabled='1'
uci set firewall.@redirect[7].src_dport='27080'
uci set firewall.@redirect[7].dest_port='27080'
uci set firewall.@redirect[7].name='SamNas npm http'
uci set firewall.@redirect[7].enabled='1'
uci set firewall.@redirect[8].src_dport='27081'
uci set firewall.@redirect[8].dest_port='27081'
uci set firewall.@redirect[8].name='SamNas npm WebUI'
uci set firewall.@redirect[8].enabled='0'
uci set firewall.@redirect[9].src_dport='27443'
uci set firewall.@redirect[9].dest_port='27443'
uci set firewall.@redirect[9].name='SamNas npm https'
uci set firewall.@redirect[9].enabled='1'
uci set firewall.@redirect[10].dest_ip='10.0.0.10'
uci set firewall.@redirect[10].src_dport='3389'
uci set firewall.@redirect[10].dest_port='3389'
uci set firewall.@redirect[10].name='Remote Desktop'
uci set firewall.@redirect[10].enabled='0'
uci commit firewall

uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci set luci.main.lang=zh_cn
uci commit luci

uci del network.globals
uci del network.lan.ip6assign
uci del network.wan6
uci set network.lan.ipaddr='10.0.0.2'
uci set network.lan.dns='119.29.29.29 114.114.114.114'
uci set network.lan.netmask='255.0.0.0'
uci set network.lan.delegate='0'
uci set network.lan.ifname='eth0 eth1 eth2 eth3 eth4 tap_vpn'
uci set network.wan.proto='pppoe'
uci set network.wan.delegate='0'
uci set network.wan.ipv6='0'
uci set network.wan.ifname='eth5'
uci set network.vlan85=interface
uci set network.vlan85.type='bridge'
uci set network.vlan85.proto='none'
uci set network.vlan85.ifname='eth4.85 eth5.85'
uci set network.vlan85.auto='1'
uci set network.vlan85.delegate='0'
uci set network.vlan51=interface
uci set network.vlan51.type='bridge'
uci set network.vlan51.proto='none'
uci set network.vlan51.ifname='eth4.51 eth5.51'
uci set network.vlan51.auto='1'
uci set network.vlan51.delegate='0'
uci commit network

uci del serverchan.serverchan.cpuload
uci set serverchan.serverchan.serverchan_enable='1'
uci set serverchan.serverchan.serverchan_up='0'
uci set serverchan.serverchan.serverchan_down='0'
uci set serverchan.serverchan.cpuload_enable='0'
# uci set serverchan.serverchan.jsonpath='/usr/bin/serverchan/api/qywx_mpnews.json'
# uci set serverchan.serverchan.mediapath='/usr/bin/serverchan/api/logo.jpg'
uci set serverchan.serverchan.device_name='SamWrt'
# uci set serverchan.serverchan.serverchan_ipv4='1'
uci set serverchan.serverchan.ipv4_interface='pppoe-wan'
# uci set serverchan.serverchan.web_logged='1'
# uci set serverchan.serverchan.ssh_logged='1'
# uci set serverchan.serverchan.web_login_failed='1'
# uci set serverchan.serverchan.ssh_login_failed='1'
# uci set serverchan.serverchan.web_login_black='0'
uci set serverchan.serverchan.login_max_num='1'
uci set serverchan.serverchan.crontab='2'
uci set serverchan.serverchan.interval_time='4'
uci set serverchan.serverchan.send_title='路由状态'
uci set serverchan.serverchan.router_status='1'
uci set serverchan.serverchan.router_temp='0'
uci set serverchan.serverchan.router_wan='1'
uci set serverchan.serverchan.client_list='1'
uci set serverchan.serverchan.serverchan_sheep='2'
uci set serverchan.serverchan.starttime='0'
uci set serverchan.serverchan.endtime='8'
uci commit serverchan

uci set system.@system[0].hostname='SamWrt'
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.ntp.enable_server='1'
uci commit system

uci set turboacc.config.sfe_flow='0'
uci set turboacc.config.fullcone_nat='1'
uci set turboacc.config.bbr_cca='0'
uci commit turboacc

uci set uhttpd.main.rfc1918_filter='0'
uci commit uhttpd

uci set upnpd.config.enabled='1'
uci commit upnpd

sed -i '/log-facility/d' /etc/dnsmasq.conf
sed -i '/dhcp-option/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf
echo 'dhcp-option-force=125,00:00:00:00:1a:02:06:48:47:57:2d:43:54:03:04:5a:58:48:4e:0a:02:20:00:0b:02:00:55:0d:02:00:2e' >>/etc/dnsmasq.conf
echo 'dhcp-option=15' >>/etc/dnsmasq.conf
echo 'dhcp-option=28' >>/etc/dnsmasq.conf
echo 'dhcp-option=60,00:00:01:06:68:75:61:71:69:6E:02:0A:48:47:55:34:32:31:4E:20:76:33:03:0A:48:47:55:34:32:31:4E:20:76:33:04:10:32:30:30:2E:55:59:59:2E:30:2E:41:2E:30:2E:53:48:05:04:00:01:00:50' >>/etc/dnsmasq.conf

#sed -i 's/root::0:0:99999:7:::/root:$1$MDmA.Fh7$15LUuc2.kXYYr3Z7VYRxt1:0:0:99999:7:::/g' /etc/shadow

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='Ver23.02.02'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='SamWrt '" >> /etc/openwrt_release

sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
sed -i '/passwall/d' /etc/opkg/distfeeds.conf
sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf

/etc/init.d/softethervpnbridge disable 2>/dev/null
/etc/init.d/softethervpnserver disable 2>/dev/null
/etc/init.d/softethervpnclient disable 2>/dev/null

echo 'hsts=0' > /root/.wgetrc

ln -sf /sbin/ip /usr/bin/ip

rm -rf /tmp/luci-*cache

rm -rf /usr/lib/lua/luci/view/admin_status/index

exit 0
