#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: 25.12 Checker

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-25.12

on:
  workflow_dispatch:
  schedule:
   - cron: 0 */12 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v5
      with:
        path: .commitHash
        key: commitHash_${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: ImmortalWrt 25.12 Update
        client-payload: |
          {
            "branch": "${{ env.REPO_BRANCH }}"
          }

    - name: Send Message to Wechat
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: HollowMan6/Wechat-Timed-Message@main
      with:
        TITLE: |
          ${{ github.repository }}
          工作流 ${{ github.workflow }} 发现更新
        CONTENT: |
          <b>编译任务已触发！！！</b>
          - 详情：<a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">点击查看</a>
        IMAGE: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/diy/openwrt.jpg
        CORPID: ${{ secrets.CORPID }}
        CORPSECRET: ${{ secrets.CORPSECRET }}
        AGENTID: ${{ secrets.AGENTID }}
